### ISSUE TITLE
Broken backstage and blank pages on new project 

### ISSUE THREAD

**Issue by RdNetwork** [architolk/Linked-Data-Theatre#10]
I managed to deploy the application (1.9.0 release) using a Tomcat 8 server.
I use a GraphDB triple store that I linked with LDT, and added the basic configuration to the 'stage' graph on my triple store, along with some example files (helloWorld, Amersroot, ...).

But nothing works in LDT: the homepage and query pages give me blank pages instead of any kind of diplay or result, and the backstage page gives the following error, repeated four times : 

```
Oeps - er ging iets mis

(resource-error)Unsupported MIME type: application/x-www-form-urlencoded 
```

GraphDB logs are a bit more explicit:

```
[INFO ] 2016-07-19 16:18:51,168 [repositories/BIO | o.o.h.s.r.s.StatementsController] POST data to repository
[INFO ] 2016-07-19 16:18:51,176 [repositories/BIO | o.o.h.s.ProtocolExceptionResolver] Client sent bad request ( 415)
org.openrdf.http.server.ClientHTTPException: Unsupported MIME type: application/x-www-form-urlencoded
```

Info and version pages are totally fine and working, though. Same for the SPARQL endpoint and its results.

Any clue? Thanks in advance

**Comment by architolk** [comment]
Could you post the config.xml file you have changed to connect it to GraphDB? This is probably the only file you have changed? We have tested LDT with GraphDB as well, so it should work. The backstage could present issues, because the backstage functionality (and the container functionality) is closely linked to Virtuoso (something to change in the future...).

The config should start with something like:
<theatre env="dev" configuration-endpoint="http://localhost:7200/repositories/ldt"
(GraphDB is running at localhost on it's default port, with a repository named "ldt")

**Comment by RdNetwork** [comment]
Indeed this is the only line I changed, the rest of the config file is the default one. (See here: http://pastebin.com/kpCckpTG )


I fixed the line by writing "http://localhost:7200/repositories/BIO" instead of "http://localhost:7200/repositories/BIO/statements" which is the usual API address required by such services.

The theatre is now working..., well, partly. It is displayed twice on each page, see here for an example: 

![ldt1](https://cloud.githubusercontent.com/assets/4118704/17049738/0c8252b2-502a-11e6-8256-4c96d9b785c0.png)
![ldt2](https://cloud.githubusercontent.com/assets/4118704/17049739/0c82adf2-502a-11e6-8695-c63f755f85af.png)

**Comment by architolk** [comment]
The issue with the multiple parts is because you have probably inserted the config twice (the number of triples should be smaller than 378). If you import a RDF file into graphDB (or Virtuoso for that matter), it doesn't clean that graph first. So you should enter sparql clear graph <http://localhost:8080/stage> first.

The issue with the linking is a bit more weird. I'm testing against the GraphDB Free version right now and I'm running into the same kind of issues, we haven't experienced this behaviour with the GraphDB Enterprise edition. What version are you using? I'm using the package 6.6.3 at this moment.

**Comment by RdNetwork** [comment]
I am using GraphDB Free 7.0.1.
I will check for the config using your advice, thanks.

**Comment by architolk** [comment]
Weird. I'm trying a configuration using the basic-configuration from a clean GraphDB endpoint and it works just fine.
One thing I found out recently: GraphDB doesn't seem to like resources without a rdf:type, I've changed the basic-configuration so every resource as a type. Maybe this helps?
