### ISSUE TITLE
Resource with , not found

### ISSUE THREAD

**Issue by GeraldGrootRoessink** [architolk/Linked-Data-Theatre#17]
Sometimes I have to work with URILs containing a komma (,).  This visibly translates to %2C in the downleft corner of Linked Data Theater  when hovering the cursor over it.  This can be expected. However, when clicking it to retrieve the resource information  at the URL, LDT will not find it. I'm sure it exists and I have seen it working with resources without a komma (,).

**Comment by architolk** [comment]
This is because the LDT is pretty strict about the allowed characters in a URI. Komma's should not appear :-). But we could relax this a bit. The file context.xsl, line 35 contains a regex expression with the allowed characters. ([^a-zA-Z0-9:\.\-_~/()#&amp;=]). By adding the komma, the resource will be found.

**Comment by architolk** [comment]
The komma is added to the allowed uri pattern in the master branch
